name: Test, compile and push app and server to production

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  tests:
    uses: Amandinelpe/City-Guide/.github/workflows/tests.yml@main

  build-and-push-server:
    needs:
      - tests
    uses: Amandinelpe/City-Guide/.github/workflows/build-server.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: ${{ secrets.DOCKERHUB_USERNAME }}/city-guide-app

  build-and-push-client:
      needs:
        - tests
      uses: Amandinelpe/City-Guide/.github/workflows/build-client.yml@main
      secrets:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      with:
        image_name: ${{ secrets.DOCKERHUB_USERNAME }}/city-guide-server

  push-on-vps:
    needs:
      - build-and-push-server
      - build-and-push-client
    uses: Amandinelpe/City-Guide/.github/workflows/deploy.yml@main
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      HOST: ${{ secrets.HOST }}
      REACT_APP_GRAPHQL_URI: ${{ secrets.REACT_APP_GRAPHQL_URI }}
      REACT_GOOGLE_API_MAPS_KEY: ${{ secrets.REACT_GOOGLE_API_MAPS_KEY }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
