name: Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          cd /home/debian/apps/City-Guide/app
          cat > .env << 'EOL'
          REACT_APP_GRAPHQL_URI=${{ secrets.REACT_APP_GRAPHQL_URI }}
          REACT_GOOGLE_API_MAPS_KEY=${{ secrets.REACT_GOOGLE_API_MAPS_KEY }}
          EOL
        
          cd /home/debian/apps/City-Guide/server
          cat > .env << 'EOL'
          PORT=${{ secrets.GRAPHQL_PORT }}
          DATABASE_TYPE=${{ secrets.DATABASE_TYPE }}
          DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          DATABASE_PORT=${{ secrets.DATABASE_PORT }}
          DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          REACT_APP_URI=${{ secrets.REACT_APP_URI }}
          EOL
        
          cd /home/debian/apps/City-Guide
          npm run stop
          npm run start
        EOF
