name: Deploy to VPS

on:
  pull_request:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      USERNAME:
        required: true
      HOST:
        required: true
      REACT_APP_GRAPHQL_URI:
        required: true
      REACT_GOOGLE_API_MAPS_KEY:
        required: true
      SERVER_PORT:
        required: true
      DATABASE_TYPE:
        required: true
      DATABASE_HOST:
        required: true
      DATABASE_PORT:
        required: true
      DATABASE_USERNAME:
        required: true
      DATABASE_PASSWORD:
        required: true
      DATABASE_NAME:
        required: true
      JWT_SECRET:
        required: true
      CORS_ALLOWED_ORIGINS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
        cd /home/debian/apps/City-Guide
        git pull origin main
        
        cd /home/debian/apps/City-Guide/app
        cat > .env << 'EOL'
        REACT_APP_GRAPHQL_URI=${{ secrets.REACT_APP_GRAPHQL_URI }}
        REACT_GOOGLE_API_MAPS_KEY=${{ secrets.REACT_GOOGLE_API_MAPS_KEY }}
        EOL

        cd /home/debian/apps/City-Guide/server
        cat > .env << 'EOL'
        SERVER_PORT=${{ secrets.SERVER_PORT }}
        DATABASE_TYPE=${{ secrets.DATABASE_TYPE }}
        DATABASE_HOST=${{ secrets.DATABASE_HOST }}
        DATABASE_PORT=${{ secrets.DATABASE_PORT }}
        DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
        DATABASE_NAME=${{ secrets.DATABASE_NAME }}
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}
        EOL

        cd /home/debian/apps/City-Guide
        npm run start
        EOF
