name: Node.js CI

on:
  push:
    branches: [ '*' ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # Ou la version de Node.js que vous utilisez

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: server
    - name: Build
      run: npm run build
      working-directory: server
    - name: Run tests
      run: npm run test
      working-directory: server
